[package]
name = "canvas"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "canvas"
path = "src/canvas.rs"

[dependencies]
anyhow.workspace = true
gpui.workspace = true
serde.workspace = true
uuid.workspace = true
