[package]
name = "luna"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "luna"
path = "src/luna.rs"

[dependencies]
anyhow.workspace = true
gpui.workspace = true
schemars.workspace = true
schemars_derive.workspace = true
serde.workspace = true
uuid.workspace = true
smallvec.workspace = true
strum.workspace = true
strum_macros.workspace = true
palette.workspace = true
taffy.workspace = true
rand = "0.9.0"
